default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: p4s3r0
  password: postgres
  host: localhost

development:
  <<: *default
  database: p4ssword_m4nager_v2

test:
  <<: *default
  database: p4ssword_m4nager_v2_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cable:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  queue:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] %>
    database: <%= ENV["DB_NAME"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
